### ISSUE TITLE
Nested if that evaluates as false breaks subsequent ifs

### ISSUE THREAD

**Issue by matthiaswh** [enthus1ast/nimja#25]
```nim
proc test2(): string = compileTemplateStr("{%if false%}{%if true%}A{%else%}B{%endif%}{%endif%}{%if true%}123{%else%}345{%endif%}")
doAssert test2() == "123" # Result is an empty string
```
If the initial `if` statement is `true` it seems to execute as expected, but if it's `false` and it contains its own nested `if` statement, the subsequent root level `if` statement never gets evaluated.

**Comment by enthus1ast** [comment]
thank you for reporting, i'll look into this

**Comment by matthiaswh** [comment]
Thanks for the quick fix. I started to dive into the code until I realized what I would be getting myself into :smiley: 

Nice work!

**Comment by enthus1ast** [comment]
The bugfix lead to greatly decreased complexity. So thanks again for reporting.
