### ISSUE TITLE
Replacement icon

### ISSUE THREAD

**Issue by jyapayne** [enthus1ast/nimja#32]
No offense to you or whoever drew the project icon, but I personally find it a bit unsettling. I came up with a new one that you are free to use if you like it better. If not, that's cool too. I have included the original svg in a zip in case you choose to use it.

![nimja](https://user-images.githubusercontent.com/2645657/133149512-68c9e08a-35fb-4b6a-9e87-72a94711c383.png)

[nimja.svg.zip](https://github.com/enthus1ast/nimja/files/7157097/nimja.svg.zip)

**Comment by jyapayne** [comment]
Haha, at least it was a fun night?

**Comment by enthus1ast** [comment]
Oh yes, but you know, when you get older, you really feel it afterwards 😁

**Comment by enthus1ast** [comment]
ok, replaced. You like it?

**Comment by jyapayne** [comment]
Looks awesome :D Thank you for using it!
