### ISSUE TITLE
variable output {{myVar}} should html encode per default

### ISSUE THREAD

**Issue by enthus1ast** [enthus1ast/nimja#38]

**Comment by enthus1ast** [comment]
not sure any more if Nimja should escape html, since other stuff then html could be templated.
Does anyone has an opinion on this?

**Comment by enthus1ast** [comment]
closed for now, if you think Nimja should, please reopen.

**Comment by ajusa** [comment]
Hm, I think it'd be nice to have Nimja escape HTML. For anyone else who finds this issue, I think you can use https://nim-lang.org/docs/xmltree.html#escape%2Cstring then use Nimja's filter syntax to escape HTML, especially if it comes from an untrusted source.
